twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Show forms with Bootstrap 4 styles
    form_themes: ['bootstrap_4_layout.html.twig']
